import pygame as pg

# define colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (215, 0, 0)
MAROON = (102, 0, 0)
PURPLE = (204, 0, 102)
GREEN = (0, 150, 0)
LIGHT_GREY = (78, 82, 84)
GREY = (60, 63, 65)
DARK_GREY = (43, 43, 43)
BLUE = (0, 0, 255)
LIGHT_BLUE = (173, 200, 240)
LIGHT_GREEN = (102, 255, 102)
YELLOW = (255, 255, 54)
DARK_GREEN = (42, 197, 42)
ORANGE = (255, 69, 0)

# load assets
# buttons
UnknownBtnIMG = pg.image.load("art/unkbtn.gif")
HaliteBtnIMG = pg.image.load("art/hltbtn.gif")
GypsumBtnIMG = pg.image.load("art/gypbtn.gif")
AnhydriteBtnIMG = pg.image.load("art/anhbtn.gif")
DolomiteBtnIMG = pg.image.load("art/dolbtn.gif")
DolomiticLSBtnIMG = pg.image.load("art/dlsbtn.gif")
ChertyDolLSBtnIMG = pg.image.load("art/cdlbtn.gif")
ChertyDolBtnIMG = pg.image.load("art/chdbtn.gif")
LimestoneBtnIMG = pg.image.load("art/lstbtn.gif")
ChertyLSBtnIMG = pg.image.load("art/chlbtn.gif")
ChertBtnIMG = pg.image.load("art/chtbtn.gif")
ShaleBtnIMG = pg.image.load("art/xshbtn.gif")
SandstoneBtnIMG = pg.image.load("art/sstbtn.gif")
IronstoneBtnIMG = pg.image.load("art/irsbtn.gif")
CoalBtnIMG = pg.image.load("art/colbtn.gif")

# images
UnknownIMG = pg.image.load("art/unk.gif")
HaliteIMG = pg.image.load("art/hlt.gif")
GypsumIMG = pg.image.load("art/gyp.gif")
AnhydriteIMG = pg.image.load("art/anh.gif")
DolomiteIMG = pg.image.load("art/dol.gif")
DolomiticLSIMG = pg.image.load("art/dls.gif")
ChertyDolLSIMG = pg.image.load("art/cdl.gif")
ChertyDolIMG = pg.image.load("art/chd.gif")
LimestoneIMG = pg.image.load("art/lst.gif")
ChertyLSIMG = pg.image.load("art/chl.gif")
ChertIMG = pg.image.load("art/cht.gif")
ShaleIMG = pg.image.load("art/xsh.gif")
SandstoneIMG = pg.image.load("art/sst.gif")
IronstoneIMG = pg.image.load("art/irs.gif")
CoalIMG = pg.image.load("art/col.gif")
